-- ASS (Automatic Solar System) Command Center Supabase Database Schema
-- Run this SQL in your Supabase SQL Editor to connect real STM32 / ESP-01 hardware

-- 1. Create Telemetry Table for Environmental Sensors
CREATE TABLE IF NOT EXISTS sensor_telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  temperature NUMERIC(4, 2) NOT NULL,
  humidity NUMERIC(4, 2) NOT NULL,
  power NUMERIC(5, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Device States Table for Control Center (Gate, Lighting, Lock, HVAC)
CREATE TABLE IF NOT EXISTS device_states (
  id INT PRIMARY KEY DEFAULT 1,
  gate_servo BOOLEAN DEFAULT FALSE,
  main_lighting BOOLEAN DEFAULT TRUE,
  lighting_brightness INT DEFAULT 80,
  hvac_power BOOLEAN DEFAULT TRUE,
  hvac_target_temp INT DEFAULT 22,
  smart_lock BOOLEAN DEFAULT TRUE,
  security_arm_state BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Hardware Alert Logs Table
CREATE TABLE IF NOT EXISTS alert_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  level TEXT CHECK (level IN ('info', 'warning', 'critical', 'success')),
  message TEXT NOT NULL,
  category TEXT CHECK (category IN ('rfid', 'sensor', 'control', 'system'))
);

-- Seed initial device state row
INSERT INTO device_states (id, gate_servo, main_lighting, lighting_brightness, hvac_power, hvac_target_temp, smart_lock, security_arm_state)
VALUES (1, FALSE, TRUE, 80, TRUE, 22, TRUE, TRUE)
ON CONFLICT (id) DO NOTHING;

-- Enable Realtime publication for tables so Next.js receives instant updates
ALTER PUBLICATION supabase_realtime ADD TABLE sensor_telemetry;
ALTER PUBLICATION supabase_realtime ADD TABLE device_states;
ALTER PUBLICATION supabase_realtime ADD TABLE alert_logs;
